### PR TITLE
add support for $_GET parameters

### PR DESCRIPTION
**Pull request by mattxo**

### CODE REVIEW

**Comment by ddprrt** [comment]
Hey @mattxo! Thanks for your help, PR looks good so far, but please keep the formatting to its original style.

**Comment by mattxo** [comment]
Pleasure @ddprrt, no probs :)

**Comment by devcken** [comment]
Hi @ddprrt. I appreciate connect-php. It is really helpful for me.
However, why doesn't merge this pull request? It may be helpful.

**Comment by ddprrt** [comment]
@devcken As said before, the code style has to be like the rest of the project. I appreciate the effort put in improving the code, but it has to be in its original formatting style to ensure save collaboraton.

**Comment by mattxo** [comment]
Oh, apologies @ddprrt, @devcken, I'm a complete newbie to contributing on GitHub, would you like me to alter the formatting and push another commit?

**Comment by ddprrt** [comment]
Hey @mattxo  -- no worries :-) Yeah, it would be nice if you could change back the formatting to its original state. The PR would be updated.

**Comment by mattxo** [comment]
Hey @ddprrt, apologies for the delay, have reversed the commit :)

**Comment by ddprrt** [comment]
Thanks @mattxo! PR is merged.

**Comment by mattxo** [comment]
Woop woop! @ddprrt

**Comment by devcken** [comment]
Great job!

**Pull request merged**
